import { defineField, defineType } from 'sanity';

export const projet = defineType({
  name: 'projet',
  title: 'Projet',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Titre du projet',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'coverImage',
      title: 'Image de couverture',
      type: 'image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'sector',
      title: 'Secteur',
      type: 'string',
      description: 'Ex: Infrastructure & BTP, Agro-industrie, Industrie…',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'client',
      title: 'Client / Partenaire',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'clientLogo',
      title: 'Logo du client',
      type: 'image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'year',
      title: 'Année',
      type: 'string',
      description: 'Ex: Décembre 2022',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'city',
      title: 'Ville',
      type: 'string',
      description: 'Ex: Dakar',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'zone',
      title: 'Zone géographique',
      type: 'string',
      description: 'Ex: Dakar, Sénégal – Corridor Corniche Ouest',
    }),
    defineField({
      name: 'services',
      title: 'Services mobilisés',
      type: 'array',
      of: [{ type: 'string' }],
      description: "Ex: Qualité de l'air, Bruit, Vibrations, Sol",
      options: {
        list: [
          { title: "Qualité de l'air", value: 'Air' },
          { title: 'Bruit', value: 'Bruit' },
          { title: 'Vibrations', value: 'Vibrations' },
          { title: 'Sol', value: 'Sol' },
          { title: 'Eau', value: 'Eau' },
          { title: 'SIG / Cartographie', value: 'SIG' },
          { title: 'EIES / PGES', value: 'EIES' },
          { title: 'QHSE', value: 'QHSE' },
          { title: 'Biodiversité', value: 'Biodiversité' },
        ],
      },
    }),
    defineField({
      name: 'standards',
      title: 'Standards appliqués',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Ex: OMS, ISO 2631, Normes sénégalaises (NS)',
    }),
    defineField({
      name: 'summary',
      title: 'Résumé (affiché sur la carte)',
      type: 'text',
      rows: 3,
      validation: (Rule: any) => Rule.required().max(200),
    }),
    defineField({
      name: 'context',
      title: 'Contexte & Enjeux',
      type: 'array',
      of: [{ type: 'block' }],
    }),
    defineField({
      name: 'intervention',
      title: 'Notre Intervention',
      type: 'array',
      of: [{ type: 'block' }],
    }),
    defineField({
      name: 'valeurAjoutee',
      title: 'Valeur ajoutée pour le client',
      type: 'text',
      rows: 4,
    }),
    defineField({
      name: 'keywords',
      title: 'Mots-clés',
      type: 'array',
      of: [{ type: 'string' }],
      description: "Ex: BTP, Dakar, SIG, Qualité de l'air",
    }),
    defineField({
      name: 'featured',
      title: 'Projet vedette',
      type: 'boolean',
      description: 'Afficher ce projet en vedette sur la page projets',
      initialValue: false,
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'client', media: 'coverImage' },
  },
});
